MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()


MACRO( INSTALL_LIBRARY target )

  file( GLOB export_header ${CMAKE_CURRENT_BINARY_DIR}/*.hpp )

  if( WIN32 )
    install( TARGETS ${target} RUNTIME DESTINATION ${INSTALL_LIBRARY_PREFIX} )
    install( FILES ${export_header} DESTINATION ${INSTALL_LIBRARY_PREFIX} )
  else( )
    install( TARGETS ${target} LIBRARY DESTINATION ${INSTALL_LIBRARY_PREFIX} )
    install( FILES ${export_header} DESTINATION ${INSTALL_LIBRARY_PREFIX} )
  endif( )
ENDMACRO()


MACRO( INSTALL_TEST target )
  if( CIE_INSTALL_TESTS )
    install( TARGETS ${target} RUNTIME DESTINATION ${INSTALL_TEST_PREFIX} )
  endif()
ENDMACRO()


MACRO( INSTALL_PYTHON_BINDINGS target moduleName )
  install( DIRECTORY DESTINATION ${INSTALL_PYTHON_MODULES_PREFIX}/${moduleName} )
  install( TARGETS ${target} LIBRARY DESTINATION ${INSTALL_PYTHON_MODULES_PREFIX}/${moduleName} )
ENDMACRO()


MACRO( INSTALL_PYTHON_MODULE moduleFolder )
  if( ${ARGC} EQUAL 1 )
    install( DIRECTORY ${moduleFolder} DESTINATION ${INSTALL_PYTHON_MODULES_PREFIX} )
  elseif( ${ARGC} EQUAL 2 )
    set( moduleName ${ARGV1} )
    install( DIRECTORY ${moduleFolder}/ DESTINATION ${INSTALL_PYTHON_MODULES_PREFIX}/${moduleName} )
  endif()
ENDMACRO()


MACRO( INSTALL_PYTHON_SCRIPTS scriptFolder )
  install( DIRECTORY ${scriptFolder}/ DESTINATION ${INSTALL_PYTHON_SCRIPTS_PREFIX}/${PROJECT_NAME} )
ENDMACRO()


MACRO( INSTALL_APPLICATION_EXECUTABLE target )
  install( TARGETS ${target} RUNTIME DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME} )
ENDMACRO()


MACRO( INSTALL_APPLICATION_LIBRARY target )
    if( WIN32 )
        install( TARGETS ${target} RUNTIME DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME} )
    else()
        install( TARGETS ${target} LIBRARY DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME} )
    endif()
ENDMACRO()


MACRO( INSTALL_APPLICATION_PYTHON_BINDINGS target )
    install( TARGETS ${target} LIBRARY DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME} )
ENDMACRO()


MACRO( INSTALL_APPLICATION_SCRIPTS )
    #install( DIRECTORY DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME}/scripts )
    #install( FILES ${ARGV} DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME}/scripts )
    install( FILES ${ARGV} DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME} )
ENDMACRO()


MACRO( INSTALL_APPLICATION_DATA )
    install( DIRECTORY DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME}/data )
    install( FILES ${ARGV} DESTINATION ${INSTALL_APPLICATION_PREFIX}/${PROJECT_NAME}/data )
ENDMACRO()


MACRO( INSTALL_DATA dataFolder )
  install( DIRECTORY ${dataFolder}/ DESTINATION ${INSTALL_DATA_PREFIX}/${PROJECT_NAME} )
ENDMACRO()