# Create install directory
install( DIRECTORY DESTINATION "${CMAKE_INSTALL_PREFIX}" )

# Executable applications
set( INSTALL_APPLICATION_PREFIX "${CMAKE_INSTALL_PREFIX}/applications" )
install( DIRECTORY DESTINATION "${INSTALL_APPLICATION_PREFIX}" )

# Dynamic libraries
set( INSTALL_LIBRARY_PREFIX "${CMAKE_INSTALL_PREFIX}/libraries" )
install( DIRECTORY DESTINATION "${INSTALL_LIBRARY_PREFIX}" )

# Executable tests
set( INSTALL_TEST_PREFIX "${CMAKE_INSTALL_PREFIX}/tests" )
install( DIRECTORY DESTINATION "${INSTALL_TEST_PREFIX}" )

# Data
set( INSTALL_DATA_PREFIX "${CMAKE_INSTALL_PREFIX}/data" )
install( DIRECTORY DESTINATION "${INSTALL_DATA_PREFIX}" )

# Python bindings
set( INSTALL_PYTHON_MODULES_PREFIX "${CMAKE_INSTALL_PREFIX}/modules" )
install( DIRECTORY DESTINATION "${INSTALL_PYTHON_MODULES_PREFIX}" )

# Python scripts
set( INSTALL_PYTHON_SCRIPTS_PREFIX "${CMAKE_INSTALL_PREFIX}/scripts" )
install( DIRECTORY DESTINATION "${INSTALL_PYTHON_SCRIPTS_PREFIX}" )

# Output
set( CIE_INSTALL_OUTPUT_PREFIX "${CMAKE_INSTALL_PREFIX}/output" CACHE STRING "output path" )
set( INSTALL_DEBUG_OUTPUT_PREFIX "${CIE_INSTALL_OUTPUT_PREFIX}/debug" )
set( INSTALL_TEST_OUTPUT_PREFIX "${CIE_INSTALL_OUTPUT_PREFIX}/test" )
install( DIRECTORY DESTINATION "${CIE_INSTALL_OUTPUT_PREFIX}" )
install( DIRECTORY DESTINATION "${INSTALL_DEBUG_OUTPUT_PREFIX}" )
install( DIRECTORY DESTINATION "${INSTALL_TEST_OUTPUT_PREFIX}" )